[language-server.tinymist]
command = "tinymist"
config = { exportPdf = "onSave", outputPath = "$dir/$name", formatterPrintWidth = 72 }

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[[language]]
name = "typst"
auto-format = true
formatter = { command = "typstyle", args = [ "-c", "72" ] }
text-width = 72
language-servers = [ "tinymist", "harper-ls" ]
