FROM node:lts-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:lts-alpine

COPY package.json package-lock.json ./

RUN npm ci --omit dev

COPY --from=builder /app/index.js .

EXPOSE 5000

ENTRYPOINT [ "node", "index.js" ]

